export const FETCH_BOOKS_START = "FETCH_BOOKS_START";
export const FETCH_BOOK_SUCCESS = 'FETCH_BOOK_SUCCESS'
export const FETCH_BOOKS_FAIL = "FETCH_BOOKS_FAIL";

export const SEARCH_DATA = 'SEARCH_DATA';

//FOR AUTH
export const AUTH_START = 'AUTH__START'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_FAIL = 'AUTH_FAIL'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'

export const SETURL = 'SETURL'
export const ADDTOWISHLIST = 'ADDTOWISHLIST'
export const REMOVEFROMWISHLIST = 'REMOVEFROMWISHLIST'

//SIDE DRAWER

export const HANDLESIDEDRAWER = 'HANDLESIDEDRAWER'
export const FILTERSIDEDRAWER = 'FILTERSIDEDRAWER'